insert into department (name, address) values ('Services', '05281 Twin Pines Alley');
insert into department (name, address) values ('Sales', '906 Knutson Circle');
insert into department (name, address) values ('Legal', '33 Summerview Road');
insert into department (name, address) values ('Services', '684 Lindbergh Way');
insert into department (name, address) values ('Human Resources', '5 Vidon Road');
insert into department (name, address) values ('Accounting', '6 Banding Junction');
insert into department (name, address) values ('Legal', '93732 Express Crossing');
insert into department (name, address) values ('Legal', '1 Spenser Center');
insert into department (name, address) values ('Human Resources', '7960 Upham Court');
insert into department (name, address) values ('Training', '65 Canary Place');
insert into department (name, address) values ('Sales', '908 Cherokee Pass');
